#!/usr/bin/env bash
# Turns the safety-check probe table into a committed bats file, one test per probe, run against
# plugins/agent-core/scripts/safety-check.sh in the fixture project the table's header describes.
#
#   bash tests/hooks/gen.sh           write tests/hooks/safety-probes.bats
#   bash tests/hooks/gen.sh --check   exit 1 when the committed file is not what the table gives
#
# The table is agent-core's template copy, plugins/agent-core/templates/common/scripts/check/
# hook-probes.tsv: the same rows setup installs into a project for scripts/check/hook-probes.sh.
# Rows are "<block|allow|warn><TAB><checkout><TAB><command>"; # lines and blank lines are skipped.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd -P)"
root="$(cd "$here/../.." && pwd -P)"
table="$root/plugins/agent-core/templates/common/scripts/check/hook-probes.tsv"
out="$here/safety-probes.bats"
check=""
case "${1:-}" in
--check) check=1 ;;
"") ;;
*)
  echo "usage: bash tests/hooks/gen.sh [--check]" >&2
  exit 2
  ;;
esac
[ -f "$table" ] || {
  echo "gen.sh: $table not found" >&2
  exit 2
}

quote() { # single-quoted for bash: ' becomes '\''
  local q="'\\''"
  printf "'%s'" "${1//\'/$q}"
}
label() { # a test name bats can hold: plain characters only, at most 60
  local s
  s="$(printf '%s' "$1" | LC_ALL=C tr -c 'A-Za-z0-9 ._/=:+-' ' ' | tr -s ' ')"
  [ "${#s}" -le 60 ] || s="${s:0:57}..."
  printf '%s' "$s"
}

generate() {
  local n=0 expect spec cmd branches=""
  cat <<'EOF'
#!/usr/bin/env bats
# shellcheck disable=SC1003,SC2016,SC2034 # each command is literal data for the hook; FIX_* are read by probe()
# GENERATED by tests/hooks/gen.sh from plugins/agent-core/templates/common/scripts/check/hook-probes.tsv.
# Do not edit by hand: change the table, then run `bash tests/hooks/gen.sh` (CI runs it with --check).
# One test per probe: plugins/agent-core/scripts/safety-check.sh must block, allow or warn exactly as
# the table says, judged in the fixture project the table's header describes (tests/helpers/common.bash
# builds it). Run as a template copy would (no CLAUDE_PLUGIN_ROOT, so no project gate);
# tests/hooks/gate.bats judges a sample of the rows in plugin mode, in a project that opted in.

load ../helpers/common

setup_file() {
  kit_isolate "$BATS_FILE_TMPDIR/env"
  probe_fixture "$BATS_FILE_TMPDIR"
EOF
  while IFS=$'\t' read -r expect spec cmd || [ -n "${expect:-}" ]; do
    case "$expect" in '' | '#'*) continue ;; esac
    if [ "$spec" != - ] && [[ " $branches " != *" $spec "* ]]; then
      branches="$branches $spec"
      # shellcheck disable=SC2016 # $BATS_FILE_TMPDIR belongs to the generated file
      printf '  probe_branch "$BATS_FILE_TMPDIR" %s >/dev/null\n' "$(quote "$spec")"
    fi
  done <"$table"
  cat <<'EOF'
}

setup() {
  kit_isolate "$BATS_FILE_TMPDIR/env"
  FIX_TMP="$BATS_FILE_TMPDIR"
  FIX_PROJ="$BATS_FILE_TMPDIR/proj"
}
EOF
  while IFS=$'\t' read -r expect spec cmd || [ -n "${expect:-}" ]; do
    n=$((n + 1))
    case "$expect" in '' | '#'*) continue ;; esac
    case "$expect" in block | allow | warn) ;; *)
      echo "gen.sh: line $n: unknown verdict '$expect'" >&2
      return 2
      ;;
    esac
    printf '\n@test "L%d %s (%s): %s" {\n  probe %s %s %s\n}\n' "$n" "$expect" "$(label "$spec")" "$(label "$cmd")" \
      "$expect" "$(quote "$spec")" "$(quote "$cmd")"
  done <"$table"
}

if [ -n "$check" ]; then
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT
  generate >"$tmp"
  if cmp -s "$tmp" "$out"; then
    echo "tests/hooks/safety-probes.bats matches the probe table ($(grep -c '^@test ' "$out") tests)"
    exit 0
  fi
  echo "::error file=tests/hooks/safety-probes.bats::stale: run bash tests/hooks/gen.sh" >&2
  exit 1
fi
generate >"$out"
echo "wrote tests/hooks/safety-probes.bats ($(grep -c '^@test ' "$out") tests)"
